---
host: http://localhost
port: '3000'
fitbit:
  clientId: ClIENT_ID
  clientSecret: CLIENT_SECRET
  apiVersion: '1.2'
  callbackRoute: "/auth/fitbit/callback"
  authRoute: "/auth/fitbit"
  dataAuthorized: activity heartrate location nutrition profile settings sleep social
    weight
  authorizationHTML: Fitbit authorized!
poller:
  enabled: false
  frequency: '3000'
  routesPolled:
  - type: standard
    resourcePath: profile
  enableWebRoutes: true
  stopPollingRoute: "/polling/stop"
  startPollingRoute: "/polling/start"
kafka:
  host: http://localhost:9092
sources:
  enableWebRoutes: true
  deleteSourceRoute: "/sources/delete"
  deactivateSourceRoute: "/sources/deactivate"
  listAllSourcesRoute: "/sources/list"
